title: Geomatics Resources
greeting: Geomatics Resources
description: A collection of useful datasets, portals, examples and documentation.
baseurl: /resources
logo: /img/jkan.png
explanation: Dummy text is also used to demonstrate the appearance of different typefaces and layouts, and in general the content of dummy text is nonsensical. Due to its widespread use as filler text for layouts, non-readability is of great importance: human perception is tuned to recognize certain patterns and repetitions in texts. If the distribution of letters and 'words' is random, the reader will not be distracted from making a neutral judgement on the visual impact and readability of the typefaces (typography), or the distribution of text on the page (layout or type area). For this reason, dummy text usually consists of a more or less random series of words or syllables. This prevents repetitive patterns from impairing the overall visual impression and facilitates the comparison of different typefaces. Furthermore, it is advantageous when the dummy text is relatively realistic so that the layout impression of the final publication is not compromised.

# Site theme
jkan_theme: Lumen

# Authentication
github_client_id: ffba000e1a7b8b8e5ff9
gatekeeper_host: https://geosdata.herokuapp.com

# Dataset schema
schema: default

# Nav bar
navigation:
  - title: Datasets
    url: /datasets/
  - title: Organizations
    url: /organizations/

# Collections
collections:
  datasets:
    output: true
    permalink: /datasets/:path/
  organizations:
    output: true
    permalink: /organizations/:path/

# Collections (cont'd)
defaults:
  - scope:
      path: ""
      type: datasets
    values:
      layout: dataset
      category: Uncategorized
      organization: N/A
  - scope:
      path: ""
      type: organizations
    values:
      layout: organization

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Google Analytics
google_analytics:
  enabled: false
  code: "UA-XXXXXX-1"

# US Digital Analytics Program - https://analytics.usa.gov
digital_analytics_program:
  enabled: false
  agency: ""
  subagency: ""

# Hypothesis.io - Annotator
hypothesis:
  enabled: false

# Twitter
twittercard:
  enabled: false
  username: "@"

# Open Graph
opengraph:
  enabled: true

# Exclude these files from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .travis.yml
  - node_modules
  - scripts/src
  - package.json
  - webpack.config.js
  - README.md
  - LICENSE
